language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
addons:
  sonarcloud:
    organization: albenoit-github
# command to run tests
script:
  - pytest -v --cov .
<<<<<<< HEAD
  - sonar-scanner
  - coveralls
=======
  #- sonar-scanner
  - coveralls
>>>>>>> 6a34285c95882b7509f8f61d8427653c5b55d703
